programa ExemploSimples {{{

   var {
      int (e)
   }

   funcao int Inserir (int a, int b)

   var {
       int (c)
   }
   comandos {
        c = a + b;
        retornar (c + glob); 
   }

    principal

    var {
        int (i, res, f, j)
    }
    comandos {

        i = 3;
        f = 10;
        res = Inserir(i, f);

        para i (0; i < 5; i + 1){
            f = f *10;
        }

        escrever(f);
    } 
}}}