programa Testing {{{

   var {
      int (g1, g2)
   }

   funcao int Test (int n1, int n2, int n3)

      var {
         int (soma)
         logic (toso)
      }

      comandos {
         soma = n1 + n2;
         retornar toso;
      }

   funcao int Test2 ()

      var {
         int (soma)
      }

      comandos {
         retornar soma;
      }

   principal 

      var {
         int (result)
      }

      comandos {
         result = Test(21.2, 2, 3);
      }

}}}